plugin-version: 1.0.0
messages:
  no_permission: "&c You not have permissions"
  kill_mob: "&fคุณได้รับ &e{amount} &fบาท จากการฆ่า &a{mob}"
  reload: "&aPlugin has reloaded"


mobs:
  ZOMBIE:
    active : true
    onSpawner: true
    min: 0.5
    max: 1
  SPIDER:
    active: true
    onSpawner: false
    min: 0.5
    max: 1